ARG NODE_ENV=development

FROM node:20.15.1-alpine

WORKDIR /opt/app

RUN apk update && apk --no-cache add curl g++ make python3 python3-dev py3-pip lz4-dev musl-dev

RUN npm install -g node-gyp

COPY package.json Makefile tsconfig.json ./
COPY assets assets
COPY templates templates
COPY schemas schemas
COPY src src

RUN npm install && npx tsc && npm prune --development

EXPOSE 8531


CMD ["npm", "run", "start"]

