SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO changelog VALUES (2, UNIX_TIMESTAMP());

CREATE TABLE oauth2_clients (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  client_id VARCHAR(50) NOT NULL UNIQUE,
  client_secret VARCHAR(50) NOT NULL,
  allowed_grant_types VARCHAR(50) NOT NULL,
  name VARCHAR(50)
);

CREATE TABLE oauth2_redirection_urls (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  oauth2_client_id INT UNSIGNED NOT NULL,
  url VARCHAR(300) NOT NULL
);

COMMIT;
