SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO changelog VALUES (3, UNIX_TIMESTAMP());

CREATE TABLE oauth2_token (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  client_id VARCHAR(50) NOT NULL,
  access_token VARCHAR(50) NOT NULL UNIQUE,
  refresh_token VARCHAR(50) NOT NULL UNIQUE,
  user_id INT UNSIGNED NOT NULL,
  access_token_expires INT UNSIGNED NOT NULL,
  refresh_token_expires INT UNSIGNED NOT NULL,
  created INT UNSIGNED NOT NULL
);

COMMIT;
