SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO changelog VALUES (9, UNIX_TIMESTAMP());

CREATE TABLE user_permissions (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  permission VARCHAR(50) NOT NULL
);

COMMIT;
