SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO changelog VALUES (11, UNIX_TIMESTAMP());

ALTER TABLE oauth2_clients
  DROP name;

ALTER TABLE users
  ADD type TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '1 = user, 2 = app';

COMMIT;
