SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO changelog VALUES (14, UNIX_TIMESTAMP());

CREATE TABLE oauth2_codes (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  client_id INT UNSIGNED NOT NULL,
  code VARCHAR(50) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  created INT UNSIGNED NOT NULL
);

COMMIT;
