SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO changelog VALUES (26, UNIX_TIMESTAMP());

CREATE TABLE reset_password_token (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  token VARCHAR(100) NOT NULL UNIQUE,
  expires_at INT UNSIGNED NOT NULL,
  created_at INT UNSIGNED NOT NULL
);

COMMIT;